# Builds R/sysdata.rda from the hand-authored crosswalks in this directory.
#
# Run with:  Rscript data-raw/build_lexicons.R
#
# The street-type crosswalk (street_types.csv) was authored against the actual
# NAR type inventory -- see nar_street_types_observed.csv, regenerated by
# data-raw/observe_street_types.R -- so every `canonical` value it emits is a
# token that really occurs in the Addresses table. Anything else would parse
# cleanly and then fail to join.

utf8 <- function(path) read.csv(path, encoding = "UTF-8", stringsAsFactors = FALSE)

# --- street types ----------------------------------------------------------
nar_lex_types <- utf8("data-raw/street_types.csv")

# How often each canonical type actually occurs in NAR. The parser uses this to
# break ties when a comma-less string offers more than one structurally valid
# place to end the street: "100 MAIN ST PORT HOPE" can read as type ST or type
# PORT, and ST outnumbers PORT 3,150,747 to 15. Unobserved types get 0.
observed <- utf8("data-raw/nar_street_types_observed.csv")
nar_lex_types$freq <- observed$n[match(nar_lex_types$canonical, observed$t)]
nar_lex_types$freq[is.na(nar_lex_types$freq)] <- 0L

# --- street directions -----------------------------------------------------
# NAR carries eleven direction tokens. The four cardinal ones plus NE/SE are
# shared between the languages, but Quebec writes Ouest as O rather than W and
# compounds it as NO/SO, so the canonical form is language-conditioned exactly
# like the street types are.
#
# Declared as canonical -> surfaces rather than three parallel vectors, because
# keeping three hand-written vectors aligned is a silent-corruption waiting to
# happen.
dir_group <- function(canonical, lang, ...) {
  surfaces <- c(...)
  data.frame(surface = surfaces, canonical = canonical, lang = lang,
             stringsAsFactors = FALSE)
}

nar_lex_dirs <- rbind(
  dir_group("N",  "both", "N"),
  dir_group("N",  "en",   "NORTH"),
  dir_group("N",  "fr",   "NORD"),
  dir_group("S",  "both", "S"),
  dir_group("S",  "en",   "SOUTH"),
  dir_group("S",  "fr",   "SUD"),
  dir_group("E",  "both", "E"),
  dir_group("E",  "en",   "EAST"),
  dir_group("E",  "fr",   "EST"),
  dir_group("W",  "en",   "W", "WEST"),
  dir_group("O",  "fr",   "O", "OUEST", "W", "WEST"),
  dir_group("NE", "both", "NE"),
  dir_group("NE", "en",   "NORTHEAST"),
  dir_group("NE", "fr",   "NORD-EST", "NORDEST"),
  dir_group("NW", "en",   "NW", "NORTHWEST"),
  dir_group("NO", "fr",   "NO", "NORD-OUEST", "NORDOUEST", "NW", "NORTHWEST"),
  dir_group("SE", "both", "SE"),
  dir_group("SE", "en",   "SOUTHEAST"),
  dir_group("SE", "fr",   "SUD-EST", "SUDEST"),
  dir_group("SW", "en",   "SW", "SOUTHWEST"),
  dir_group("SO", "fr",   "SO", "SUD-OUEST", "SUDOUEST", "SW", "SOUTHWEST")
)

# --- provinces -------------------------------------------------------------
nar_lex_prov <- data.frame(
  surface = c("NL", "NFLD", "NEWFOUNDLAND", "NEWFOUNDLAND AND LABRADOR",
              "TERRE-NEUVE", "TERRE-NEUVE-ET-LABRADOR",
              "PE", "PEI", "IPE", "PRINCE EDWARD ISLAND", "ILE-DU-PRINCE-EDOUARD",
              "NS", "NOVA SCOTIA", "NOUVELLE-ECOSSE",
              "NB", "NEW BRUNSWICK", "NOUVEAU-BRUNSWICK",
              "QC", "PQ", "QUE", "QUEBEC",
              "ON", "ONT", "ONTARIO",
              "MB", "MAN", "MANITOBA",
              "SK", "SASK", "SASKATCHEWAN",
              "AB", "ALTA", "ALBERTA",
              "BC", "CB", "BRITISH COLUMBIA", "COLOMBIE-BRITANNIQUE",
              "YT", "YUKON",
              "NT", "NWT", "NORTHWEST TERRITORIES", "TERRITOIRES DU NORD-OUEST",
              "NU", "NUNAVUT"),
  canonical = c(rep("NL", 6),
                rep("PE", 5),
                rep("NS", 3),
                rep("NB", 3),
                rep("QC", 4),
                rep("ON", 3),
                rep("MB", 3),
                rep("SK", 3),
                rep("AB", 3),
                rep("BC", 4),
                rep("YT", 2),
                rep("NT", 4),
                rep("NU", 2)),
  stringsAsFactors = FALSE
)

# Which canonicalization language a province takes. Quebec is the only province
# whose NAR street types are overwhelmingly French (RUE/AV/BOUL run 94-100% QC);
# New Brunswick is officially bilingual but its NAR rows use the English tokens
# by a wide margin, so it stays "en".
nar_prov_lang <- c(NL = "en", PE = "en", NS = "en", NB = "en", QC = "fr",
                   ON = "en", MB = "en", SK = "en", AB = "en", BC = "en",
                   YT = "en", NT = "en", NU = "en")

# --- unit designators ------------------------------------------------------
# Words that introduce a unit rather than being one. Order matters only in that
# the parser matches the longest first.
nar_lex_unit_words <- c("APARTMENT", "APPARTEMENT", "APT", "APP", "UNIT", "UNITE",
                        "UNITÉ", "SUITE", "STE", "BUREAU", "BUR", "ROOM", "RM",
                        "LOCAL", "DEPARTMENT", "DEPT", "FLOOR", "FL", "ETAGE",
                        "ÉTAGE", "LEVEL", "NIVEAU", "PENTHOUSE", "TOWNHOUSE",
                        "NO", "NUM", "NUMBER", "NUMERO", "NUMÉRO")

# Bare unit tokens that stand alone with no number, and are stored in
# APT_NO_LABEL verbatim. BSMT alone accounts for 137,413 NAR rows.
# MAIN, FRONT, REAR and SIDE are deliberately absent: each is a common street
# name (Front St, Main St) and only rarely a unit label, so listing them costs
# far more than it gains.
nar_lex_unit_bare <- c("BSMT", "BASEMENT", "SOUS-SOL", "PH", "PENTHOUSE",
                       "LOWER", "UPPER")

# --- numbered rural roads --------------------------------------------------
# Roads the prairie grid and its cousins name with a phrase plus a number and
# no street type at all: NAR stores `Range Road 272` as OFFICIAL_STREET_NAME
# with OFFICIAL_STREET_TYPE empty. Measured over the 2026-06 Streets table,
# counting addresses:
#
#   Range Road      AB 65,464 / SK 258      Route          NB 51,000
#   Township Road   AB 33,599               Concession     ON  7,490
#   County Road     ON    550               Mun            MB    963
#   Concession Road ON    442               Regional Road  ON    249
#
# Highways are deliberately absent: `Highway 7` is filed the ordinary way, as
# name `7` with type `HWY` (115,175 rows), so putting HIGHWAY here would break
# the commonest numbered road in the country to fix none of these.
#
# `prov` gates an entry to one province and is empty for the rest. Only ROUTE
# needs it, and needs it badly: New Brunswick's typeless `Route 105` (51,000)
# and Quebec's `Route 132` as name `132` type `ROUTE` (113,827) are the same
# five characters meaning opposite things. An entry with a `prov` set does not
# fire when the province is unknown, which leaves the commoner reading alone.
#
# Left out on purpose, all under ~1,500 addresses each and each colliding with
# a real street type or name: bare `Road N` (ON/MB), `Sideroad N`, `Sideline N`,
# `Firelane N`, `Old Highway N`, and Quebec's `Descente N`.
numbered_road <- function(canonical, prov, ...) {
  data.frame(surface = c(...), canonical = canonical, prov = prov,
             stringsAsFactors = FALSE)
}

nar_lex_numbered_roads <- rbind(
  numbered_road("RANGE ROAD",      "", "RANGE ROAD", "RANGE RD", "RGE ROAD", "RGE RD"),
  numbered_road("TOWNSHIP ROAD",   "", "TOWNSHIP ROAD", "TOWNSHIP RD",
                                       "TWP ROAD", "TWP RD"),
  numbered_road("CONCESSION ROAD", "", "CONCESSION ROAD", "CONCESSION RD",
                                       "CONC ROAD", "CONC RD"),
  numbered_road("CONCESSION",      "", "CONCESSION", "CONC"),
  numbered_road("COUNTY ROAD",     "", "COUNTY ROAD", "COUNTY RD",
                                       "CTY ROAD", "CTY RD", "CO RD"),
  numbered_road("REGIONAL ROAD",   "", "REGIONAL ROAD", "REGIONAL RD",
                                       "REG ROAD", "REG RD"),
  numbered_road("MUN",             "", "MUN", "MUNICIPAL ROAD", "MUNICIPAL RD"),
  numbered_road("ROUTE",         "NB", "ROUTE", "RTE")
)

# --- folded match keys -----------------------------------------------------
# Matching is accent-insensitive, but output is not: NAR stores MONTÉE and
# ALLÉE with their accents, so the parser matches on `surface_fold` and emits
# `canonical` verbatim. Folding here rather than at runtime keeps the hot path
# free of stringi calls.
fold <- function(x) {
  stringi::stri_trans_general(toupper(stringi::stri_trans_nfc(x)), "Latin-ASCII")
}

nar_lex_types$surface_fold <- fold(nar_lex_types$surface)
nar_lex_dirs$surface_fold  <- fold(nar_lex_dirs$surface)
nar_lex_prov$surface_fold  <- fold(nar_lex_prov$surface)
nar_lex_unit_words <- unique(fold(nar_lex_unit_words))
nar_lex_unit_bare  <- unique(fold(nar_lex_unit_bare))
nar_lex_numbered_roads$surface_fold <- fold(nar_lex_numbered_roads$surface)

save(nar_lex_types, nar_lex_dirs, nar_lex_prov, nar_prov_lang,
     nar_lex_unit_words, nar_lex_unit_bare, nar_lex_numbered_roads,
     file = "R/sysdata.rda", version = 3, compress = "xz")

cat("Wrote R/sysdata.rda:",
    nrow(nar_lex_types), "type surfaces,",
    nrow(nar_lex_dirs), "direction surfaces,",
    nrow(nar_lex_prov), "province surfaces\n")
